/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { RolePermissionService } from "../rolePermission.service";
import { RolePermissionCreateInput } from "./RolePermissionCreateInput";
import { RolePermission } from "./RolePermission";
import { RolePermissionFindManyArgs } from "./RolePermissionFindManyArgs";
import { RolePermissionWhereUniqueInput } from "./RolePermissionWhereUniqueInput";
import { RolePermissionUpdateInput } from "./RolePermissionUpdateInput";

export class RolePermissionControllerBase {
  constructor(protected readonly service: RolePermissionService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: RolePermission })
  async createRolePermission(
    @common.Body() data: RolePermissionCreateInput
  ): Promise<RolePermission> {
    return await this.service.createRolePermission({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [RolePermission] })
  @ApiNestedQuery(RolePermissionFindManyArgs)
  async rolePermissions(
    @common.Req() request: Request
  ): Promise<RolePermission[]> {
    const args = plainToClass(RolePermissionFindManyArgs, request.query);
    return this.service.rolePermissions({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: RolePermission })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async rolePermission(
    @common.Param() params: RolePermissionWhereUniqueInput
  ): Promise<RolePermission | null> {
    const result = await this.service.rolePermission({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: RolePermission })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateRolePermission(
    @common.Param() params: RolePermissionWhereUniqueInput,
    @common.Body() data: RolePermissionUpdateInput
  ): Promise<RolePermission | null> {
    try {
      return await this.service.updateRolePermission({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: RolePermission })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteRolePermission(
    @common.Param() params: RolePermissionWhereUniqueInput
  ): Promise<RolePermission | null> {
    try {
      return await this.service.deleteRolePermission({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
